[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
    'chmod +x deploy.sh',
    'chmod +x start.sh',
    './deploy.sh'
]

[phases.build]
cmds = []

[start]
cmd = "ls -la start.sh && chmod +x start.sh && bash start.sh"