[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
    'chmod +x deploy.sh',
    './deploy.sh'
]

[phases.build]
cmds = []

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'