[build]
builder = "NIXPACKS"

[deploy]
startCommand = "echo 'Starting Laravel...' && php -v && php artisan --version && php artisan config:clear && php artisan migrate --force || echo 'Migration failed' && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health.php"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"