# Railway Hosting Deployment Configuration

# Build Command
composer install --optimize-autoloader --no-dev && php artisan config:cache && php artisan route:cache && php artisan view:cache

# Start Command  
php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT