[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health.php"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE" 