[build]
builder = "NIXPACKS"

[deploy]
startCommand = "mkdir -p bootstrap/cache storage/logs storage/framework/{cache,sessions,views} storage/app/public && chmod -R 755 bootstrap/cache storage && php artisan migrate --force && (php artisan db:seed --force || echo 'Seeding completed') && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
# Production optimizations
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"

# Performance settings (use database since we may not have Redis)
CACHE_DRIVER = "database"
SESSION_DRIVER = "database"  
QUEUE_CONNECTION = "database"

# Security
SESSION_SECURE_COOKIE = "true"
SESSION_HTTP_ONLY = "true"
SESSION_SAME_SITE = "strict" 