[build]
builder = "NIXPACKS"

[deploy]
startCommand = "echo 'Starting Laravel Debug Mode...' && php -v && php artisan --version && php artisan config:clear && echo 'Testing database connection...' && php artisan migrate:status || echo 'Migration status failed' && php artisan migrate --force || echo 'Migration failed' && echo 'Starting server...' && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/debug"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"