[build]
builder = "NIXPACKS"

[deploy]
startCommand = "echo 'Starting PHP server directly...' && php -v && echo 'Current directory:' && pwd && echo 'Files in root:' && ls -la && echo 'Files in public:' && ls -la public/ && php -S 0.0.0.0:$PORT -t public/"
healthcheckPath = "/test.php"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"